name: finmentor_ai
description: FinMentor AI - Financial Literacy App for ASEAN Youth
publish_to: 'none'
version: 1.0.0+1

environment:
  sdk: '>=3.0.0 <4.0.0'

dependencies:
  flutter:
    sdk: flutter
    # Firebase
  firebase_core: ^2.30.0
  firebase_auth: ^4.17.4
  cloud_firestore: ^4.15.7
  firebase_storage: ^11.6.9
  cloud_functions: ^4.6.5
  # Firebase extras
  firebase_analytics: ^10.8.9
  http: ^1.2.0
  google_fonts: ^6.1.0
  fl_chart: ^0.68.0
  curved_navigation_bar: ^1.0.3
  animate_do: ^3.3.4
  provider: ^6.1.5+1

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^3.0.0

flutter:
  uses-material-design: true