// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCzapTPcwTH6sOAvcHJjupAd4nZreeYsU8',
    appId: '1:270531377629:web:ff5cf2ea5b9ce4ab539e34',
    messagingSenderId: '270531377629',
    projectId: 'finmentorai-2026',
    authDomain: 'finmentorai-2026.firebaseapp.com',
    storageBucket: 'finmentorai-2026.firebasestorage.app',
    measurementId: 'G-0KTZJ0YH6D',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCdxY-nXxjAjlIvHMNUKyzdAjXG1wZ-7UQ',
    appId: '1:270531377629:android:61bc98d931fa59fc539e34',
    messagingSenderId: '270531377629',
    projectId: 'finmentorai-2026',
    storageBucket: 'finmentorai-2026.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyC5s-SnwHb5MzJwynD80jOd1-lUQPF0Clo',
    appId: '1:270531377629:ios:df7fd178821e5f03539e34',
    messagingSenderId: '270531377629',
    projectId: 'finmentorai-2026',
    storageBucket: 'finmentorai-2026.firebasestorage.app',
    iosBundleId: 'com.example.frontend',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyC5s-SnwHb5MzJwynD80jOd1-lUQPF0Clo',
    appId: '1:270531377629:ios:df7fd178821e5f03539e34',
    messagingSenderId: '270531377629',
    projectId: 'finmentorai-2026',
    storageBucket: 'finmentorai-2026.firebasestorage.app',
    iosBundleId: 'com.example.frontend',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyCzapTPcwTH6sOAvcHJjupAd4nZreeYsU8',
    appId: '1:270531377629:web:10c92f3420e974f5539e34',
    messagingSenderId: '270531377629',
    projectId: 'finmentorai-2026',
    authDomain: 'finmentorai-2026.firebaseapp.com',
    storageBucket: 'finmentorai-2026.firebasestorage.app',
    measurementId: 'G-GLZP6MV58P',
  );
}
